// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfjVyMlIkzhQ-JS5QIwRQ45D54j0zj4v0',
    appId: '1:548346443732:web:e9025b930bb3e4a71c0841',
    messagingSenderId: '548346443732',
    projectId: 'project-ca33f',
    authDomain: 'project-ca33f.firebaseapp.com',
    storageBucket: 'project-ca33f.appspot.com',
    measurementId: 'G-CNEKZJSWQ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVtCpIJAgu3U6RGZ_l5m-qVcSXPjiVCJM',
    appId: '1:548346443732:android:d4fe45714e0d54941c0841',
    messagingSenderId: '548346443732',
    projectId: 'project-ca33f',
    storageBucket: 'project-ca33f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZziYBW05KKTUWR5Kyzso4fPzCdzjqyQQ',
    appId: '1:548346443732:ios:cdf1d0403e0b2aa61c0841',
    messagingSenderId: '548346443732',
    projectId: 'project-ca33f',
    storageBucket: 'project-ca33f.appspot.com',
    iosClientId: '548346443732-7p4ceesl50rl3p7gk9m205ohoasqqvne.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZziYBW05KKTUWR5Kyzso4fPzCdzjqyQQ',
    appId: '1:548346443732:ios:00b25e369fb514cf1c0841',
    messagingSenderId: '548346443732',
    projectId: 'project-ca33f',
    storageBucket: 'project-ca33f.appspot.com',
    iosClientId: '548346443732-6sec20gh2o7kadmt0f7g4oejrmca2qdl.apps.googleusercontent.com',
    iosBundleId: 'com.example.project.RunnerTests',
  );
}
